# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 464e0d21192650c40613e872687f3aa6f5532b89f5626cfc8e5e24fe417290a070732146853aa343968062dd4c0807262c68d8f3a5512e803ccc246cd9be77d7

test:
  secret_key_base: 9e5d8328adc823fa02d1b355a5cb192f577570b1fc40145ff92e729382a52c1a91a1c668c7350bc4add2eb1b60b5ae9a8609ba879ae61ec37c8890867a424aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
